name: convokit_flutter_ui_examples
description: Runnable examples for configuring and customizing the ConvoKit Flutter UI package.
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  convokit_flutter: ^0.3.1
  convokit_flutter_ui: ^0.3.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
